### ISSUE TITLE
disagreement between survivaltime.get_plsep_ov and Equation (61)

### ISSUE THREAD

**Issue by shadden** [acpetit/PlanetSysSurvivalTime#2]
Hey Antoine-- 
 I noticed that the function `survivaltime.get_plsep_ov` appears to disagree with Eq 61 from your paper for equal-mass, equal-spacing systems. Specifically, the numerical coefficent 1.16 appearing in Eq. (61) appears to just be 1.0 when using the function. Of course, I may simply be misinterpreting something...  I've included a minimum working example below:

```
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append("modules")
import survivaltime as st 
%matplotlib inline

ms = np.logspace(-7,-3)
Pov = np.zeros(len(ms))
delta_ov  = np.zeros(len(ms))
for i,m in enumerate(ms):
    delta_ov[i] = st.get_plsep_ov(1/(1+.01),1/(1+0.01),m * np.ones(3))
    Pov[i] = (1-2*delta_ov[i])**(-1.5)
plt.plot(ms,delta_ov,'bo',label="numerical")
plt.plot(ms,1.16 * (ms**(1/4)),'k-',label="Eq. 61")
plt.plot(ms, (ms**(1/4)),'r--',label="$\mu^{1/4}$")
plt.xscale('log')
plt.yscale('log')
plt.legend()
```

**Comment by dtamayo** [comment]
I remember talking with Antoine a couple years ago when I was working through the paper, and I think Eq 61 should be 1.00 instead of 1.16 if you work through it from Eq 59, and I think Antoine updated the code, but he can confirm!

**Comment by acpetit** [comment]
Hi Sam, I confirm that there is a typo in the paper that Dan found in 2021. I the function gives the right value and all figures on the paper were correct. I have added a list of known typos in the paper to the Readme.

**Comment by shadden** [comment]
Thanks!
